import React, { useContext, useState } from 'react';
import { View, Text, StyleSheet, TextInput, ScrollView, TouchableOpacity } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import ThemeContext from '../context/ThemeContext';
import ResultList from '../flatlists/ResultsList';
import CreatePlaylistButton from '../Buttons/CreatePlaylistButton';
import getPlaylistData from '../api/GetTempPlaylists';
import ImageUploader, { selectedImageB64 } from '../imageUploader/ImageUploader';
import { CreatePlaylist } from '../api/Spotify - Playlist/SpotifyCreatePlaylist';
import { AddCoverImage } from '../api/Spotify - Playlist/SpotifyAddCustomCover';
import { AddItemsToPlaylist } from '../api/Spotify - Playlist/SpotifyAddItemsToPlaylist';
import { UserContext } from '../context/UserDetailsContext';
import { useAccessToken } from '../api/Spotify - Util/SpotifyUseAccessToken';


const EditPlaylistDetailsScreen = () => {
  const { theme } = useContext(ThemeContext);
  const { userDetails } = useContext(UserContext);
  const accessToken = useAccessToken();

  const userId = userDetails.userId;
  const displayName = userDetails.displayName;

  const [playlistName, setPlaylistName] = useState('User Generated Playlist');
  const [playlistDescription, setPlaylistDescription] = useState(`A playlist generated by ${displayName}`);
  


  const uris = [ //very temp. delete asap!
    "spotify:track:7ycWLEP1GsNjVvcjawXz3z",
    "spotify:track:04tGB3iBg3EFjmHt7XmOoO",
    "spotify:track:5iWkcEcUfymaq0POyWCbBQ",
    "spotify:track:3tTDOodJcr6vKF2DASlwMZ"
];

  ///// work in progress
  const handleCreatePlaylist = async () => {
    try {
        const playlistId = await CreatePlaylist({accessToken, userId, playlistName, playlistDescription});
        //await AddCoverImage({accessToken, playlistId, selectedImageB64}); //does not currently work, image is too big
        await AddItemsToPlaylist({accessToken, playlistId, uris});

    } catch (error) {
        console.error('Error creating playlist:', error);
        alert('Failed to create playlist. Please try again.');
    }
};
  ///// work in progress

  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme === 'dark' ? '#2B2B2B' : '#FCFCFC',
    },
    content: {
      flexGrow: 1,
      alignItems: 'center',
      padding: 30,
    },
    imageText: {
      fontSize: 20,
      marginBottom: 40,
      color: theme === 'dark' ? '#FCFCFC' : '#2B2B2B',
    },
    input: {
      height: 40,
      width: 250,
      borderColor: theme === 'dark' ? '#FCFCFC' : '#2B2B2B',
      borderWidth: 1,
      borderRadius: 10,
      marginBottom: 15,
      paddingHorizontal: 15,
      color: theme === 'dark' ? '#FCFCFC' : '#2B2B2B',
    },
    results: {
      flex: 1,
      width: '80%',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
    },
    leftText: {
      textAlign: 'left',
      color: theme === 'dark' ? '#FCFCFC' : '#2B2B2B',
    },
    rightSection: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    listContainer: {
      paddingLeft: 15,
      marginBottom: 15,
    },
  });

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <ImageUploader />
      <Text style={styles.imageText}>Change cover art</Text>

      <View>
        <TextInput
          style={styles.input}
          placeholder="Enter playlist name"
          value={playlistName}
          onChangeText={setPlaylistName}
        />

        <TextInput
          style={styles.input}
          placeholder="Enter playlist description"
          value={playlistDescription}
          onChangeText={setPlaylistDescription}
        />
      </View>

      <View style={styles.results}>
        <View style={styles.row}>
          <Text style={styles.leftText}>Your choices:</Text>
            <TouchableOpacity style={styles.rightSection} onPress={() => alert("Edit button pressed!")}>
            <Text style={{ color: theme === 'dark' ? '#FCFCFC' : '#2B2B2B' }}>Edit</Text>
            <Ionicons name="create-outline" size={24} color={theme === 'dark' ? '#FCFCFC' : '#2B2B2B'} />
            </TouchableOpacity>
        </View>
        <View style={styles.listContainer}>
          <ResultList data={getPlaylistData()} imgSize={40} headingSize={14} descriptionSize={12} />
        </View>
      </View>
      <CreatePlaylistButton onPress={handleCreatePlaylist}/>
    </ScrollView>
  );
};

export default EditPlaylistDetailsScreen;
